import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=process.cwd(),base='openspec/changes/frade-p01-theme-core',dir=path.resolve(base+'/evidence/p01-focus-passive-diagnostic-20261008T055500Z'),mode=process.argv[2];
assert(['controls','clones'].includes(mode));fs.mkdirSync(dir,{recursive:true});const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),save=(n,v)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),source='apps/desktop/tests/e2e/ui-contract-theme.spec.ts';
const full=base+'/evidence/p01-refresh-full-root-20261008T034000Z/source-before.json',manifest=JSON.parse(fs.readFileSync(full)),pins={[source]:'7c3e52a69c1b8346a78f4297774f5c2342a3ecdaeb05a2611465d2f09c546f43','apps/desktop/src/main/drawio-theme-bridge.ts':'53901d117d50c9efc5abf3d4590f8e1ba699a28a042641f9bccdb070e64e218a','apps/desktop/tests/unit/drawio-theme.test.ts':'0badcdf4e787d8c3bf148c397f16f5046c6bfc55196aa32fc60a7b6ca99eb2e4','apps/desktop/out/main/index.cjs':'d0a3bb1920e8464543e732ca5b7ced13583a5b0b8300432b17f3d7ab7d2853a9'};
const verify=()=>{const files=manifest.files.map(v=>{const b=fs.readFileSync(v.path);return {...v,actualSha256:sha(b),actualBytes:b.length}}),protectedFiles=Object.entries(pins).map(([p,s])=>({path:p,expected:s,actual:sha(fs.readFileSync(p))}));return {atUtc:new Date().toISOString(),manifest:full,manifestSha256:sha(fs.readFileSync(full)),count:files.length,changed:files.filter(v=>v.sha256!==v.actualSha256||v.bytes!==v.actualBytes),protectedFiles,pass:files.every(v=>v.sha256===v.actualSha256&&v.bytes===v.actualBytes)&&protectedFiles.every(v=>v.actual===v.expected)}};
const dc='Get-CimInstance Win32_VideoController | Select-Object Name,CurrentHorizontalResolution,CurrentVerticalResolution,CurrentRefreshRate,VideoModeDescription | ConvertTo-Json -Depth 3',display=()=>{const r=spawnSync('powershell.exe',['-NoProfile','-Command',dc],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);return {atUtc:new Date().toISOString(),command:dc,controllers:JSON.parse(r.stdout)}};
const before=verify();save(mode+'-source-before.json',before);assert(before.pass,'SOURCE_CHANGED');const db=display();save(mode+'-display-before.json',db);assert([db.controllers].flat().some(c=>c.CurrentHorizontalResolution===2560&&c.CurrentVerticalResolution===1440&&c.CurrentRefreshRate>=60),'DISPLAY_CHANGED');
if(mode==='controls'){fs.copyFileSync(process.argv[1],path.join(dir,'run.mjs'),fs.constants.COPYFILE_EXCL);fs.copyFileSync(source,path.join(dir,'original-test-source.bin'),fs.constants.COPYFILE_EXCL);}else{const controls=JSON.parse(fs.readFileSync(path.join(dir,'controls-completion.json')));assert(controls.sourceAfter.pass&&controls.executions===2,'CONTROL_PROTOCOL_INCOMPLETE');assert(JSON.parse(fs.readFileSync(path.join(dir,'clone-proof.json'))).pass,'CLONE_PROOF_FAILED');}
const original=fs.readFileSync(path.join(dir,'original-test-source.bin'));assert(fs.readFileSync(source).equals(original));const candidate=mode==='clones'?Buffer.concat([original,fs.readFileSync(path.join(dir,'diagnostic-tail.txt'))]):original;
const names=mode==='controls'?['P01-UPPER-028 actual owned popup foreground contrast and focus raster dark comfortable','P01-UPPER-031 actual body focus bounds media neighbors and modal light comfortable']:['P01-FOCUS-DIAGNOSTIC-028 actual owned popup foreground contrast and focus raster dark comfortable','P01-FOCUS-DIAGNOSTIC-031 actual body focus bounds media neighbors and modal light comfortable'];
const regex='(?:'+names.join('|')+')$',pnpm='C:/Users/NVISEN/AppData/Local/node/corepack/v1/pnpm/12.6.0/bin/pnpm.mjs',command=[process.execPath,pnpm,'--filter','@frade/desktop','exec','playwright','test','tests/e2e/ui-contract-theme.spec.ts','--workers=1','--retries=0','--repeat-each='+(mode==='clones'?3:1),'--grep',regex,'--reporter=json','--output='+path.join(dir,mode+'-artifacts')],report=path.join(dir,mode+'-report.json');
const start={atUtc:new Date().toISOString(),mode,scope:'PASSIVE_DIAGNOSTIC_NOT_GATE',command,names,fixedExecutions:mode==='clones'?6:2,sourceSha256:sha(original),candidateSha256:sha(candidate),prefixExact:candidate.subarray(0,original.length).equals(original),pre:'p01-focus-diagnostic-pre-received-20261008T054219Z',displayUserReportedHz:60.01};save(mode+'-start.json',start);
const status='docs/ui/UI-DESIGN-CONTRACT-STATUS.md';let s=fs.readFileSync(status,'utf8');s=s.replace(/^Обновлено .*?\. Ветка/m,'Обновлено '+new Date().toISOString()+'. Ветка').replace(/^\| RCA \|.*$/m,'| RCA | PRE PASS; '+mode.toUpperCase()+' RUNNING; fixed2controls/6passive observations; no repair |').replace(/^Следующий шаг:.*$/m,'Следующий шаг: завершить фиксированный диагностический protocol и сохранить все outcomes. Текущие2FAIL остаются открытыми; код продукта не меняется.').replace(/^Git:.*$/m,'Git: PRE checkpoint64f8f6cf2ed203c03199e447ba44035c01e20a19 PUSHED_REMOTE_SHA_VERIFIED2026-10-08T05:44:19.715Z. Current diagnostic UNCOMMITTED. UI origin/ref only; branch protection LOCAL_ONLY/NOT_CONFIGURED; right panel queued, visibility unconfirmed.');fs.writeFileSync(status,s);const cp=base+'/execution-context.json',c=JSON.parse(fs.readFileSync(cp));c.phase='P01_FOCUS_DIAGNOSTIC_'+mode.toUpperCase()+'_RUNNING';c.currentFocusDiagnostic={run:path.relative(root,dir).replaceAll('\\','/'),mode,status:'RUNNING',fixedControlExecutions:2,fixedCloneExecutions:6,pre:'PASS',fullRoot:'FAIL2',sourceChanges:'TEMPORARY_APPEND_ONLY_CLONES_EXACT_RESTORATION'};fs.writeFileSync(cp,JSON.stringify(c,null,2)+'\n');
let exitCode=null,error=null,restored=mode==='controls';const out=fs.openSync(path.join(dir,mode+'-stdout.txt'),'wx'),err=fs.openSync(path.join(dir,mode+'-stderr.txt'),'wx');
try {if(mode==='clones')fs.writeFileSync(source,candidate);console.log(JSON.stringify({status:'RUNNING',mode,dir,executions:start.fixedExecutions}));const child=spawn(command[0],command.slice(1),{cwd:root,env:{...process.env,PLAYWRIGHT_JSON_OUTPUT_FILE:report},stdio:['ignore',out,err],windowsHide:true});exitCode=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve)});}catch(e){error=String(e);}finally{fs.closeSync(out);fs.closeSync(err);if(mode==='clones'){if(fs.readFileSync(source).equals(candidate)){fs.writeFileSync(source,original);restored=true;}else error=(error||'')+' UNEXPECTED_CONCURRENT_WRITE_NO_RESTORE';}}
const sourceAfter=verify(),da=display();save(mode+'-display-after.json',da);let cases=[];if(fs.existsSync(report)){const data=JSON.parse(fs.readFileSync(report));const visit=s=>{for(const x of s.specs||[])for(const t of x.tests)cases.push({title:x.title,status:t.status,results:t.results.map(r=>({status:r.status,duration:r.duration,retry:r.retry,errors:r.errors}))});for(const x of s.suites||[])visit(x)};visit(data);}
const completion={atUtc:new Date().toISOString(),mode,exitCode,error,sourceAfter,restored,tailAbsent:fs.readFileSync(source).equals(original),executions:cases.reduce((n,c)=>n+c.results.length,0),cases,displayUnchanged:JSON.stringify(db.controllers)===JSON.stringify(da.controllers),scope:'DIAGNOSTIC_ONLY_FULL_FAILURES_REMAIN_OPEN'};save(mode+'-completion.json',completion);console.log(JSON.stringify({mode,exitCode,error,executions:completion.executions,results:cases.map(c=>({title:c.title,status:c.status})),sourcePass:sourceAfter.pass,restored}));process.exitCode=error||!sourceAfter.pass||!restored?2:exitCode??2;
