import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {performance} from 'node:perf_hooks';
const owner='C:/Users/NVISEN/.codex/worktrees/ui-design-contract/frade';assert.equal(process.cwd().replaceAll('\\','/'),owner);
const mp='C:/Users/NVISEN/AppData/Local/Temp/frade-ui-p02-current.json',m=JSON.parse(await fs.readFile(mp,'utf8')),stamp=new Date().toISOString(),dir=m.base+'/evidence/p02-bootstrap-delete-ownership-probe-'+stamp.replace(/[-:.]/g,'');await fs.mkdir(dir);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const source=await fs.readFile('packages/extension-service/native/windows-filesystem.cs'),meta=JSON.parse(await fs.readFile('packages/extension-service/dist/native/integrity.json','utf8')),exe=path.resolve('packages/extension-service/dist/native/frade-filesystem.exe'),asset=await fs.readFile(exe);
assert.equal(meta.sourceSha256,sha(source));assert.equal(meta.executableSha256,sha(asset));assert.equal(meta.sourceSha256,'73ec4d15c7a91abb4d0dcc0d11b88bf2b91e209f222514cad4a24f1654580377');
const tempParent=await fs.realpath(os.tmpdir()),temp=await fs.mkdtemp(path.join(tempParent,'frade-p02-bootstrap-ownership-')),root=path.join(temp,'extensions'),outside=path.join(temp,'outside');await fs.mkdir(root);await fs.mkdir(outside);await fs.writeFile(path.join(outside,'sentinel'),'outside-original');
const startedAtUtc=new Date().toISOString(),start=performance.now(),child=spawn(exe,[],{stdio:'pipe',windowsHide:true,shell:false}),session=crypto.randomUUID(),events=[];let id=0,clock=0,received=start,buffer='',pending=null,stderr='';
const exit=new Promise(resolve=>child.once('close',resolve));child.stderr.on('data',b=>{stderr+=b.toString();if(stderr.length>4096)child.kill();});child.on('error',e=>pending?.reject(e));child.stdout.on('data',b=>{buffer+=b.toString('utf8');if(buffer.length>131072){pending?.reject(Error('FRAME_LIMIT'));child.kill();return;}const n=buffer.indexOf('\n');if(n<0)return;const line=buffer.slice(0,n);buffer=buffer.slice(n+1);const p=pending;pending=null;if(!p){child.kill();return;}clearTimeout(p.timer);try{const reply=JSON.parse(line);assert.equal(reply.requestId,id);assert.equal(reply.session,session);assert.equal(reply.generation,1);assert.equal(reply.version,1);clock=reply.clockMs;received=performance.now();events.push({reply});p.resolve(reply);}catch(e){p.reject(e);}});
const send=(operation,fields={})=>new Promise((resolve,reject)=>{assert(!pending);assert(performance.now()-start<60000);const now=id===0?0:Math.floor(clock+performance.now()-received),command={version:1,session,generation:1,requestId:++id,deadlineMs:now+10000,operation,...fields};events.push({command});pending={resolve,reject,timer:setTimeout(()=>{child.kill();reject(Error('COMMAND_TIMEOUT'));},10000)};child.stdin.write(JSON.stringify(command)+'\n');});
let result,cleanup='NOT_RUN';try{
assert.equal((await send('bind',{root})).status,'ACK');assert.equal((await send('mkdir',{path:['probe']})).status,'ACK');
const bytes=Buffer.from('owned-capability-payload'),opened=await send('write-open',{path:['probe','pending.tmp'],maxBytes:bytes.length});assert.equal(opened.status,'ACK');assert.equal((await send('write-chunk',{handle:opened.handle,offset:0,data:bytes.toString('base64')})).status,'ACK');assert.equal((await send('write-close',{handle:opened.handle,sha256:sha(bytes)})).status,'ACK');assert.equal((await send('replace',{handle:opened.handle,parent:['probe'],name:'final.bin',sha256:sha(bytes)})).status,'ACK');
const before=await send('list',{path:['probe'],limit:128,cursor:null});assert.equal(before.status,'ACK');const originalId=before.entries.find(e=>e.name==='final.bin').identity;
await fs.rename(path.join(root,'probe','final.bin'),path.join(root,'probe','retained-original.bin'));await fs.writeFile(path.join(root,'probe','final.bin'),'replacement-sentinel',{flag:'wx'});
const changed=await send('list',{path:['probe'],limit:128,cursor:null});assert.equal(changed.status,'ACK');const replacementId=changed.entries.find(e=>e.name==='final.bin').identity;assert.notEqual(replacementId,originalId);
const removed=await send('remove',{path:['probe','final.bin'],kind:'file'});const after=await send('list',{path:['probe'],limit:128,cursor:null});assert.equal(after.status,'ACK');const replacementDeleted=!after.entries.some(e=>e.name==='final.bin');assert.equal(await fs.readFile(path.join(root,'probe','retained-original.bin'),'utf8'),bytes.toString());
await fs.writeFile(path.join(root,'probe','unexpected.bin'),'unknown-ordinary-child',{flag:'wx'});const directoryRemove=await send('remove',{path:['probe'],kind:'directory'});const rootAfter=await send('list',{path:[],limit:128,cursor:null});assert.equal(rootAfter.status,'ACK');
result={status:'REPRODUCED_BOOTSTRAP_CLEANUP_OWNERSHIP_GAP',leaf:{originalId,replacementId,genuineSwap:true,removeStatus:removed.status,replacementDeleted,originalBytesPreservedBeforeDirectoryProbe:true},directory:{genuineUnknownChildCreated:true,removeStatus:directoryRemove.status,probeDirectoryDeleted:!rootAfter.entries.some(e=>e.name==='probe')},implication:'Current checked remove proves actual object type/confinement but does not compare a caller-expected prior identity or provide empty-only directory deletion. Source-only inspection was insufficient; concrete bootstrap cleanup needs a contract decision.'};
assert.equal(removed.status,'ACK');assert(replacementDeleted);assert.equal(directoryRemove.status,'ACK');assert(result.directory.probeDirectoryDeleted);
assert.equal((await send('dispose')).status,'ACK');
}catch(e){result={status:'BLOCKED_PROBE',error:{message:e.message,stack:e.stack}};}
finally{if(child.exitCode===null&&child.signalCode===null)child.kill();await Promise.race([exit,new Promise((_,reject)=>setTimeout(()=>reject(Error('EXIT_TIMEOUT')),10000))]);assert.equal(await fs.readFile(path.join(outside,'sentinel'),'utf8'),'outside-original');assert.deepEqual(await fs.readdir(outside),['sentinel']);const resolved=await fs.realpath(temp);assert.equal(path.dirname(resolved).toLowerCase(),tempParent.toLowerCase());assert(path.basename(resolved).startsWith('frade-p02-bootstrap-ownership-'));await fs.rm(resolved,{recursive:true});cleanup='REMOVED_OWNED_TEMP_FIXTURE';}
const record={startedAtUtc,finishedAtUtc:new Date().toISOString(),head:m.head,sourceSha256:sha(source),executableSha256:sha(asset),limits:{oneHelper:true,oneOwnedTempRoot:true,maxWallMs:60000,maxOperationMs:10000,maxFrameBytes:131072,productionWrites:0},durationMs:performance.now()-start,...result,cleanup,outsideBytesAndCount:'UNCHANGED',kind:'Bounded diagnostic against exact shipped-source helper, not a changed regression assertion, live user profile or capability certification'};
await fs.writeFile(dir+'/probe.json',JSON.stringify(record,null,2)+'\n',{flag:'wx'});await fs.writeFile(dir+'/events.json',JSON.stringify(events,null,2)+'\n',{flag:'wx'});await fs.writeFile(dir+'/stderr.txt',stderr,{flag:'wx'});await fs.copyFile(process.argv[1],dir+'/probe.mjs');m.bootstrapOwnershipProbe={dir,...record};m.phase='P02_S0_BOOTSTRAP_CLEANUP_SCOPE_DECISION_REQUIRED';await fs.writeFile(mp,JSON.stringify(m,null,2)+'\n');console.log(JSON.stringify({dir,...record}));process.exitCode=result.status==='BLOCKED_PROBE'?2:0;
