import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root='C:/Users/NVISEN/.codex/worktrees/ui-design-contract/frade';
const state='C:/Users/NVISEN/AppData/Local/Temp/frade-ui-p02-current.json';
const m=JSON.parse(await fs.readFile(state,'utf8'));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=a=>execFileSync('D:/Program Files/Git/mingw64/bin/git.exe',['-c','core.longpaths=true','-c','core.autocrlf=false',...a],{cwd:root,encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});
assert.equal(git(['branch','--show-current']).trim(),'codex/frade-ui-design-contract');
assert.equal(git(['status','--porcelain=v1','--untracked-files=all']),'');
assert.equal(m.s1Revalidation.POST,'PASS');
const at=new Date().toISOString(),dir=m.base+'/evidence/p02-s2-scheme-'+at.replace(/[-:.]/g,'');
await fs.mkdir(root+'/'+dir); await fs.mkdir(root+'/'+dir+'/before');
const scheme=dir+'/s2-scheme.md';
const text=`# P02 S2 — staging / journal / recovery / named bridge scheme

${at}. Planning refinement requested by the human after current focused S1 POST PASS. Owning branch codex/frade-ui-design-contract; worktree ${root}; common E:/dev/codex/frade/.git; checkpoint ${m.head}; P02 baseline 0ecaf44938382bd8daa7d512887dda8a8ee9b372; cumulative origin 98f387f96b51b0ad139e3507c376ff1c3e8dec09. Guide and Themes-and-Plugins-Spec v1.0. S2 production NOT_IMPLEMENTED, PRE NOT_RUN. No claim that S1 proves transaction recovery. Tasks remain3/9: 2.2/2.3 unchecked; no P03.

## 1. Authority, objective and strategy before expensive work

Use complete active proposal/design/spec/tasks and accepted integration, Windows backend, ancestor handoff, bootstrap owned cleanup and P02-D01 decisions. Current S1 receipt: ${m.s1Revalidation.post.dir}/verification.json. Historical S1 POST FAIL and original dev5000ms FAIL remain immutable; only exact P02-D01 is deferred, cause NOT_PROVEN. No fourth DEV diagnostic attempt, timeout change or current failure waiver.

Objective: implement one bounded, injected coordinator over the live verified filesystem, with safe immutable package storage, seven-phase journal, COMMITTED-only recovery authority, P01 presentation agreement and named Electron transport. Completion evidence requires meaningful RED/GREEN, actual NTFS kill/reopen, guards, source binding and independent POST. This PRE reviews the scheme and implementation boundaries; it does not assert those future tests passed or close full P02.

Material alternatives:

| Alternative | Cost / dependencies / risks | Choice |
|---|---|---|
| Existing full feature in one implementation/review batch | Forecast several work sessions; high debugging and packet cost; mixes storage, runtime and UI uncertainty. No measured completion probability. | Keep cumulative closure later; do not start with this batch. |
| Existing ports + immutable archive blob + sequential coordinator slices | Forecast scheme/validation30–60min and PRE8–20min; implementation S2 several sessions, uncertain until first probe. Bounded50MiB archive+200MiB validator memory; no native API expansion. Small packages first; actual maximum/kill coverage remains mandatory. | Selected. |
| Extract all files then promote a directory | Up to10000 file creations plus probe/journal exceeds existing helper lifetime creation budget; cross-parent/directory rename is absent. New native protocol would need architecture scope. | Inapplicable in current closed protocol; exact ZIP blob retains all original file bytes without this work. |
| Mutable registry/latest pointer or separate presentation journal | Less code initially, but conflicts with immutable chain and single COMMITTED authority. | Inapplicable; no contract weakening. |
| Node path checks / native operation additions | Node cannot replace accepted checked handles. New operations/fields require a separate exact decision and PRE. | Inapplicable unless bounded proof identifies a real blocker. |
| Reuse verified S1 evidence and incremental checks | Current S1 tests266/BDD266 measured67–74s test time, reviews17–18min measured. Reuse only exact unchanged applicable input coverage; new coordinator/transport need fresh RED/GREEN. Token cost unmeasured. | Selected; no duplicate full S1 run before planning PRE. |
| Parallel native writers / foreign worktree state | Violates one lease/coordinator and feature ownership. Independent portable checks may be parallel where they do not compile/write shared outputs. | Only safe independent checks; implementation slices serial. |

Initial bounded probe after PRE: one compatible paired-theme install into a task-owned NTFS root through shipped helper, exact archive bytes/hash, eight-record maximum accounting, no active selection change, then actual process kill at one precommit and one postcommit boundary. Before broader matrix, record command/byte/handle counts and durations. Unknown/FAIL, hash drift, missing ownership or existing timeout violation stops for RCA; reassess before another expensive run. Probe is evidence, not replacement for complete phase/effect matrix. Source-reading feasibility here confirms existing read/list/exclusive chunk write/flush/same-parent absent-target publication/identity-remove operations; runtime feasibility NOT_RUN.

## 2. Concrete files and dependency direction

Planned new host modules under packages/extension-service/src: storage.ts (checked adapter), journal.ts (canonical records/scan/quota), coordinator.ts (serialized state machine), recovery.ts (idempotent reconciliation). Export only host entrypoints through existing index.ts. Portable DTO/parser additions stay in packages/extension-contracts/src and named packages/runtime-contracts/src/extensions.ts; runtime-contracts/src/index.ts exports them. No service/Node/Electron/UI/domain import into portable contracts. Service receives plain presentation snapshots and injected lifecycle ports; it never imports P01 UI or repository journals.

Existing approved Main adapter apps/desktop/src/main/extension-installer.ts owns fixed userData/extensions and live certificate; Main/index.ts wires startup, file dialog, named IPC, generation and close. presentation-settings.ts owns its already authorized settings files and injected coordinator ports. New preload/extension-bridge.ts and renderer/extension-bootstrap.ts expose portable named methods. Allowed P01 integration is only theme/index.ts, registry.ts, types.ts and later ThemePicker.tsx for revisioned registry adoption; service.ts, resolver, participant/barrier implementations and original P01 assertions remain frozen. Changes in index.ts decorate existing ports, not a rewrite of the transaction algorithm. If those ports prove insufficient, STOP for exact planning/scope repair before editing another file.

Root/manifests/boundary hooks and new tests are restricted to the accepted path table; no new dependency selected by this scheme. Extensions Workbench UI belongs task2.4, not this source slice. No routing/domain/vendor/Draw/brand/tokens/CI/shared policy edits; no dependency on Routing V2.

## 3. Storage layout and immutable byte ownership

Under the one checked root: .coordinator.lock (existing native lease), journal/records (one authoritative chain), versions/<archiveSHA256>/archive.frade-extension (exact compressed immutable bytes), and staging/<transactionUUID> (bounded owned transaction metadata, never a latest pointer). Proposed names are service-owned validated components, never renderer paths. Directory establishment is existing non-authoritative metadata category; package/staging/version/registry/presentation effects start only after durable STAGING. Existing .frade-runtime-probe remains finite bootstrap-only and absent after successful S1 proof.

The selected archive is opened read-only in Main after the actual dialog, read with an actual50MiB limit, then detached into a privately owned bounded buffer. Hash and validate that same buffer with current validatePackage and actual app0.1.0/API1.0.0/canonical roles. No external path reopen, untrusted mutation or renderer archive bytes; no writes to the chosen source. Validation in memory before STAGING permits a complete bounded old/new plan. It does not waive VALIDATED: after STAGING and checked chunk copy, read back the stored archive, hash and validate it again before registration. All200MiB expanded/count10000/ratio100/depth32/CRC/path/schema limits remain. Original incompatible sample remains byte-identical, rejected with no package/state writes.

Keep ZIP as immutable version data instead of promoting expanded files: native P02 is declarative themes only. Full ZIP preserves all package bytes; enabled theme descriptors are bounded validated projections in memory, not persisted derived data or executable files. Both Light and Dark register together. No directory/cross-parent rename or new native command is needed. Each new version directory and blob is referenced by durable STAGING before creation; content exists before logical publication and is not current until valid COMMITTED. If the hash directory already exists, completely validate its exact ordinary inventory/hash/manifest/compatibility; reuse exact bytes or block corrupt/conflicting state, never overwrite/merge. A crash mid-write is a known owned uncommitted candidate, not a valid version. Current and retained previous archives stay protected. No unconditional power-loss claim.

Archive read/write streams are serialized chunks≤64KiB, frame≤128KiB, file≤200MiB. Close each non-publication blob with retainForPublication:false. Journal publication≤1MiB alone retains its source handle. Count all service file creations and probe allowance against native10000 lifetime budget; reserve package/metadata plus8 journal creations before STAGING. When no transaction/disposition remains open, host may await actual disposal, reacquire same authorized root with fresh generation/certificate, perform full recovery and reread revision before further admission. During the lease gap commands are refused; another legitimate coordinator is handled by fresh state/CAS, never two writers. Never rotate/clear counters mid-transaction, weaken the native guard, or treat a session reset as recovery. Required stress covers the boundary and restart. Physical disk exhaustion is still UNKNOWN/REFUSED/BLOCKED, not guaranteed by logical quotas.

## 4. Journal encoding, scan and reservation

One exact UTF-8 canonical JSON encoding, schema1, safe integer global ordinal, transactionUUID, expected registry revision, previousRecordSHA256, record kind, bounded payload and payloadSHA256. Records have full identical old/new registry snapshots, version references, full old/new PresentationRecord values, finite cleanup intents and immutable envelope. Hash filename uses exact record bytes, not reserialized guesses or a self-referential hash field. Final:20digitOrdinal.transactionUUID.recordSHA256.json. Pending: .pending-<transactionUUID>-<hostSessionGeneration>-<plannedOrdinal>-<operationUUID>.tmp, same retained journal/records parent. First predecessor null with validated fresh baseline; every following predecessor is exact previous bytes. Ordinal/IDs derive from coordinator sequence, never renderer/mtime/Date.now/DOM order.

Checked full scan includes every entry/actual byte, validates disjoint bounded names, ordinary identity, exact hash/schema/canonical encoding and contiguous ordinal/state/revision chain. Max10000 slots/100MiB actual journal bytes, each payload/record≤1MiB as applicable controlling design. Gaps/forks/conflicts/duplicate ordinals/illegal transitions/truncated authoritative finals/unknown names/types are RECOVERY_BLOCKED. Recognized owned pending temps are not authority, count until safely removed, and cannot excuse a malformed final. Complete chain selects an outcome before any cleanup effect. Only an otherwise fresh root with no contradictory installed data permits first-ordinal owned pending cleanup; unclear ownership preserves bytes and blocks.

Before any STAGING/effect reserve8 slots and8*1048576 bytes for complete seven-phase+one closing-disposition outcome. Validate worst-case complete old/new record payloads and finite error metadata in advance; reject if any record cannot fit. Admission usedSlots+unspentReservedSlots+8≤10000 and usedBytes+unspentReservedBytes+8388608≤104857600. One open transaction. Pending publication consumes its planned record slot; rename does not create a second slot. After crash derive unspent envelope from validated STAGING/actual records; never allocate a second reserve or allow later admission to consume it.

Publication uses existing write-open/chunks/write-close(retain:true)/replace: held ordinary source, same strong parent, absent final name, ReplaceIfExistsFALSE, NT class10/NULLRootDirectory, successful status+IO_STATUS, same identity/hash/size and identical write-through/flush/readback before ACK. Existing identical or conflicting final never permits overwrite. Possible-effect failure makes session unusable and outcome UNKNOWN; fresh full scan may reuse exact matching final as already published, never blindly retry mutation. No head pointer, second journal, compaction or history deletion.

## 5. Transaction sequence and commit boundary

| Durable intent | Effect permitted only after intent ACK / condition |
|---|---|
| STAGING | Create bounded owned staging metadata and candidate version blob; old registry/presentation remains authoritative; admission reserve already held. |
| VALIDATED | After stored exact ZIP validation, prepare immutable candidate registration view; no activation. |
| PREPARED | Cancel/reconcile preview, acquire lifecycle veto/quiescence and prepare P01 consumers with the candidate snapshot while preserving dirty editor identity. |
| SWAPPED | After actual prepare completion, install provisional in-memory registry generation under the painted neutral cover; journal still selects old until COMMITTED. |
| PRESENTATION_ACK | After exact participant paint acknowledgements, persist/read back planned Main settings and verify candidate registry/version/presentation; no reveal/success. |
| COMMITTED | Only after all actual checks and coherent generations; successful durable publication establishes sole new-state authority. Lost reply does not undo marker. Then permit reveal/success, not earlier. |
| CLEANUP | Record at most one bounded immutable physical cleanup intent, release package handles and attempt checked cleanup without deleting current/retained bytes. |

Finally verify actual registry/settings/version and publish at most ONE same-chain RecoveryDisposition (RETAINED_COMMITTED or ROLLED_BACK), referring valid COMMITTED or baseline/prior authority and actual state hashes. It is not an eighth PHASE. Before this closing receipt no later transaction, even after success ACK. Cleanup locks may remain CLEANUP_PENDING with truthful diagnostics; closing receipt does not assert absent locked bytes. Release unspent envelope after confirmed closing disposition. Physical retries/restarts reuse intent+receipt, append no records and persist no derived done counters.

Registry logical pointer is reconstructed from this chain and checked archives, not another mutable disk file. Provisional swaps are internal under barrier; public queries return last coherent state plus busy, not a mixed candidate. Failure before valid marker restores old; after marker retains new. All install/update/enable/disable/remove/actual-retained rollback and durable presentation interactions use the same serialized authority and expected revision, one active version/ID. Unsupported capabilities/executable contributions refuse before use.

## 6. P01 bridge algorithm and lost-ACK guard

P01's frozen service has actual prepare→barrier.paint→all participant.apply ACKs→host.persist→participant.reveal/barrier.reveal points. The integration in allowed theme/index.ts decorates its existing barrier/host ports. PREPARED intent precedes service preparation; decorated apply barrier first paints the existing cover, then requests SWAPPED intent+provisional registry adoption, before original service invokes apply. Decorated host.persist receives the exact validated apply context after all participant ACKs, requests PRESENTATION_ACK intent, performs existing Main persistence/readback and COMMITTED publication, then returns the original shape of durable ACK. No new phase or weakening of P01 validation, retries, CAS, membership,2s participant/5s host deadlines or original5000ms initial show timeout.

For install with no active presentation impact, run the coordinator with exact identical old/new presentation (no settings write/revision bump) and registry prepare/adoption acknowledgements under the same cover; no surprise activation. For active update/disable/remove/rollback resolve candidate via sole P01 resolver; same stable ThemeId retains choice, absent/disabled preferred uses builtin of matching resolved kind, preserving mode/density/other settings. Lifecycle save/convert/cancel is an injected veto only; no implemented custom editor or icon provider is advertised.

Ordinary durable picker/mode/density commits after a journal-backed registry exists also enter the same coordinator as a no-package-change transaction, so closing snapshots cannot be invalidated by a separate unjournalled settings writer. Preview/environment refresh remains nonpersistent. On a genuinely fresh builtin-only root before the first installer journal, unchanged standalone P01 persistence is its baseline. This is required single-authority coordination through accepted Main/index/presentation-settings and controller ports, not a new standalone persistence API. Concurrency tests cover first install racing ordinary P01 commit and normal selection followed by restart; capture actual durable baseline after serialized ownership, never stale boot settings.

P01 compensation first calls barrier.paint with rollback context. The decorated rollback barrier must reconcile COMMITTED authority BEFORE any rollback participant effect. If valid COMMITTED exists, refuse old-state compensation, retain cover and RECOVERY_BLOCKED until coherent new-state recovery; never restore old behind a valid marker. If precommit, journal-bound restoration may proceed and its actual settings/version readback is required before closing ROLLED_BACK. If helper/publish unknown, revoke the old transaction generation; late callbacks cannot write/reveal/commit until fresh scan resolves authority. Bare errors/cached success/renderer receipt do not choose state. Existing settings reconcile is not an authorization to overwrite coordinator-chosen committed state.

Main-only recovery settings port in presentation-settings.ts validates journal-authorized exact PresentationRecord and target state, stages/syncs/renames/readbacks using existing authorized settings storage and its schema; no generic renderer restore and no extension helper sibling writes. Boot recovery can restore the exact recorded old/new durable record before initialize resolves its registry; live compensation coordinates actual P01 owner/revision and verifies resulting record, never assumes a callback restored bytes. If this cannot retain agreed record/CAS semantics within existing ports, STOP rather than silently weakening the contract. No effect after generation invalidation. Tests must distinguish actual lost-ACK and valid-marker races from mocks.

## 7. Recovery before paint and shutdown

Main initializes certificate+exclusive lease, performs full chain/blob validation and chooses old for every incomplete prefix before valid COMMITTED, new after marker. Restore/reconcile actual registry + Main settings and validate referenced current/required previous bytes before creating boot projection. Repeated restoration after crash is idempotent; existing exact closing receipt is verified/reused, not duplicated. Missing/corrupt authority/required bytes, unsafe entries or failed restore => RECOVERY_BLOCKED with bytes retained, no builtin reset. Missing optional previous rollback bytes yield explicit unavailable diagnostic, never recreated version.

Main recovery precedes BrowserWindow/bootstrap first paint: presentation-settings resolution receives only committed enabled descriptors; preload obtains bounded committed registry boot projection agreeing on revision/generation/hash with the presentation boot, validated before createRoot/ready. Changed renderer bootstrap paths are accepted S2 integration, not the narrower historical DEV diagnostic exception. Keep original show/readiness5000ms and dirty-work mounted-editor contracts. A typed pre-effect backend-unavailable plus truly absent install root alone retains existing builtin workbench; present/unsafe/unknown installed state blocks.

Close invalidates extension selection/session/generation/callbacks, settles pending operations honestly and awaits real helper disposal with existing repository/backend/dirty-close guard. Accepted S1 disposal behavior remains. Unknown/failed close never reports success. Failed recovery cannot be fixed by changing startup timeout, clearing settings or deleting a probe.

## 8. Named DTO/IPC boundary

Planned portable named methods: getBoot/listInstalled, choosePackageFile, installSelected, updateSelected, setEnabled, remove, rollbackRetained, getDiagnostics, subscribe. Internal bounded lifecycle prepare/apply/reconcile requests carry exact transaction context; no raw fs/IPC/service objects. New contract parsers require exact version1, bounded request/session IDs, safe generation/revision integers and closed payload keys; deny host paths, renderer archive bytes, unexpected fields and executable grants. Main validates actual sender webContents/mainFrame/trusted origin plus session/generation, one request ownership and monotonic deadline BEFORE effects. Subframes/forged/stale/replayed/duplicate/oversize calls refuse.

File dialog returns cancel or an opaque single-use Main-owned selection token bound to window/session/generation, exact selected-byte SHA and deadline. Token never embeds path or grants a reusable arbitrary file read. Main holds one bounded selection buffer≤50MiB per session, disposes/replaces on cancel/expiry/window close and consumes once at admission, then frees memory. UI sees declared package metadata/hash/provenance only after validation; paths/logs/secrets stay host-only. Transport limits proposed within accepted new DTO purpose: request32KiB, reply/event≤1MiB with bounded pagination; metadata string160, diagnostic code80/message512, one outstanding mutation, finite subscriptions disposed on close. Token lifetime60s measured with host monotonic clock, not semantic domain state. Oversized boot projections block rather than truncate; no synchronous bulk ZIP in preload. Exact runtime constants/parsers are part of S2 RED before production.

GetBoot must run over already recovered state, before presentation controller creation. Preload can retrieve a bounded synchronous committed projection using a named boot channel, as existing presentation boot does; other methods asynchronous named transport. validate matching projection registryHash/revision/generation before root apply; no renderer-selected generation/source trust. New APIs remain separate from existing health/repository/workbench contracts. No enabled Extensions action until its real integration exists.

## 9. Meaningful RED / BDD and evidence map

| Existing obligations | Required new behavioral assertions (not yet executed) |
|---|---|
| P02PKG001–006 / task2.2 | Actual bounded selected-byte read/copy, exact original/derived hashes, paired choices/no activation, corrupt/changed blob refusal, all archive limits retained, zero chosen-source/project writes and checked outside-root hashes. |
| P02TX001 / task2.3 | Actual killed process at every intent/effect, pre/post valid COMMITTED, before/after reply and disposition; fresh process uses real NTFS+shipped helper and original prefix hashes, distinct from thrown-error tests. |
| P02TX002–004 / FS003 | Forced uncertain publish/readback/settings effects, valid-marker lost ACK blocks old compensation before its first effect; exact chain/canonical/hash/filename/ordinal/gap/fork/conflict rejection; recognized partial pending vs malformed authoritative. |
| Complete outcome reservation |7vs8 slots;8MiB-1vs8MiB;8 maximum-size records; crash retains remaining envelope; second admission cannot spend it; repeated startup/locked cleanup adds no record; native lifetime budget and safe between-transaction rebind. |
| P02TX005 / LIFE001–005 | Actual retained ZIP rollback and absent/corrupt prior bytes, active update/fallback matrix; unsafe editor save-fail/cancel veto; real Windows locks truthful pending/retry; enable/reinstall no surprise selection. |
| Runtime/bridge / task2.2 | RED for forged/stale/duplicate/token reuse/session expiry/oversize/subframe/origin, no privileged objects/deep imports; close invalidates subscriptions and no late effect; actual dialog/token/installer proof separate from injected-port tests. |
| P01 coordination / UI004–005 | Existing frozen algorithm tested with new port decorators: ordinary picker commit+journal restart, install races, preview cancel, active update, precommit restore and postmarker retain, first boot registry/presentation agreement, actual settings bytes and dirty editor/domain/selection bytes. |

New service tests in packages/extension-service/tests and native actual temp fixtures; new runtime-contract parser tests; approved new apps/desktop/tests/unit/extension*.test.ts or p02*.test.ts; portable packages/ui-workspace/tests/ui-contract/p02*.test.ts[x]; existing P02 e2e may gain new cases without changing old assertions. Original archive59/protocol43/native89/host26/deployment9/factory and P01 assertions/pins/evidence stay intact. RED must fail on a deterministic unimplemented behavior through an existing callable fixture, not merely missing import. Before production fixes record genuine reproducer/expectation; after two failed deterministic fixes STOP/RCA.

## 10. Delivery slices, checks and limits

S2a: injected checked blob storage+journal encoding/publisher/scan/reservation RED→GREEN; no renderer registration until ready. S2b: coordinator+actual recovery+guards and killed-process matrix. S2c: named contracts/Main/preload/bootstrap/controller port decorators, then exact S2 verification and automatic POST. Each slice retains applicable checks and does not bypass required pre/post controls; material scope repair gets fresh PRE. Task2.2 checked only after its entire service/filepicker/bridge obligations;2.3 only after actual full recovery matrix;2.4 remains later Extensions UI. Do not claim all2.2 on storage alone.

Actual package named typecheck/lint/test/test:bdd, native build/deploy/runtime evidence, desktop/runtime/ui unit/integration/targeted Electron, root boundaries/check:all, token/color/contrast compliance and applicable a11y/visual remain required. Use source-bound evidence and actual command/exits; unchanged-input reuse needs explicit equivalence. Sequential native compilers/runtime writers. Fresh exact plan PRE/POST gpt-6-sol/xhigh via shared1.1 release a3ac63b52187e1f45f08b6d0beffcd67425c491d8ae1ac5d0d0efd3832e73fd0; actual backend/effort NOT_CONFIRMED. One immutable packet/fresh canary/full candidate binding; no duplicated preliminary canary or integrity waiver. Old product test PASS is not new S2 PASS.

No visual migration in scheme. When actual controls/boot theme behavior changes: FDS001–018 as applicable; EXT001–005/007/010–012; A11Y001/002/003/004/005/007/008/009, Light/Dark/HC×compact/comfortable, keyboard/forced-colors/coarse/reduced-motion/reflow and actual screenshots/current state errors. Human visual acceptance separate from machine/review PASS. Later imports/icons/hosts/native APIs/network registry/profiles remain P03–P07, not implemented here. Merge protection LOCAL_ONLY/NOT_CONFIGURED. Full P02 READY_FOR_VERIFY:NO until remaining tasks/checks/cumulative verify/POST/visual acceptance/archive. Scheme/PRE checkpoint may be committed/pushed only to authorized UI ref, STOP before P03.
`;
await fs.writeFile(root+'/'+scheme,text,{flag:'wx'});
const artifacts=['proposal.md','design.md','tasks.md','specs/extension-installer/spec.md']; const changed=[];
for(const p of artifacts){const file=m.base+'/'+p,old=await fs.readFile(root+'/'+file);await fs.mkdir(root+'/'+dir+'/before/'+p.split('/').slice(0,-1).join('/'),{recursive:true});await fs.writeFile(root+'/'+dir+'/before/'+p,old,{flag:'wx'});let addition='';
 if(p==='proposal.md')addition=`\n## Current S2 planning checkpoint\n\n${at}: user-requested [S2 scheme](${scheme.slice(m.base.length+1)}) concretizes existing accepted staging/journal/recovery/bridge goals. Current focused S1 POST PASS (${m.s1Revalidation.post.dir}/verification.json) supersedes earlier dated pending-S1 claims only. Exact ZIP blobs preserve package bytes without new native commands; one seven-phase coordinator and P01 port decorators retain COMMITTED authority and all prior security/gates. No new product capability or scope expansion; no production edits. Full3/9,2.2/2.3unchecked; S2 PRE NOT_RUN, fullREADY_FOR_VERIFY:NO. Historical P02-D01/rawFAIL unchanged.\n`;
 if(p==='design.md')addition=`\n## Current controlling S2 scheme and selected execution strategy\n\n${at}: human requested concrete S2 planning and automatic PRE after current S1 POST PASS. Adopt [complete S2 scheme](${scheme.slice(m.base.length+1)}) as the implementation algorithm/refinement for remaining2.2/2.3; it preserves all controlling original requirements, exact accepted paths and model table. Scheme sections1–10 define alternatives/costs/bounded probe, immutable ZIP storage, complete quota/hash-chain authority, actual prepaint recovery, P01 existing-port decorators/lost-ACK guard, Main-only recovery settings and named bounded bridge, meaningful RED/kill evidence and sequential slices. No native protocol field/operation, P01 service algorithm or timeout changes. Current3/9; S2 production/PRE NOT_RUN, task2.4/full closure remainopen. No original historical evidence/decision/controls move. Strict and fresh exact-role automatic PRE must PASS before new S2 production.\n`;
 if(p==='tasks.md')addition=`\n## Current S2 execution detail — tasks remain unchecked\n\n${at}: current S1 focused POST PASS, published${m.head}; historical rawFAIL/P02-D01causeNOT_PROVEN preserved. [Complete S2 scheme](${scheme.slice(m.base.length+1)}) refines remaining2.2/2.3 inside accepted scope. S2a storage+journal+reservation RED/GREEN; S2b single coordinator/actual NTFS process-kill recovery; S2c named DTO/Main/preload/bootstrap/P01port integration and partial verify/automaticPOST. Every full2.2/2.3 assertion remains required before checking tasks;2.4ExtensionsUI remains later. Current3/9, strict/PRE NOT_RUN for this refinement, no S2 implementation. No new task checkmark or automaticP03.\n`;
 if(p==='specs/extension-installer/spec.md')addition=`\n## Implementation traceability for existing S2 requirements\n\n${at}: [S2 scheme](../../${scheme.slice(m.base.length+1)}) maps the unchanged requirements/scenarios to immutable exact archive storage, existing checked commands, one reserved seven-phase journal/closing disposition, COMMITTED-only recovery and named bridge/P01 ports. No new or weakened normative requirement or scenario; all original spec text above remains byte-present. Current focused S1 POST PASS does not prove these S2 obligations, which remain NOT_IMPLEMENTED/NOT_RUN until meaningful RED/GREEN and applicable gates.\n`;
 await fs.writeFile(root+'/'+file,Buffer.concat([old,Buffer.from(addition)]));changed.push({path:file,beforeSha256:sha(old),afterSha256:sha(await fs.readFile(root+'/'+file)),originalBytesRetained:true});}
const controls=m.diagnostics.sourceFiles;for(const f of controls)assert.equal(sha(await fs.readFile(root+'/'+f.path)),f.sha256);
const sourceControls=[];for(const p of git(['ls-files','--','packages/extension-service','packages/extension-contracts','packages/runtime-contracts','packages/ui-workspace/src/design','apps/desktop/src','apps/desktop/tests','docs/ui/bdd','docs/ui/Themes-and-Plugins-Spec.md','docs/ui/Frade-UI-Style-Guide.md','package.json','pnpm-lock.yaml']).split(/\r?\n/).filter(Boolean)){const b=await fs.readFile(root+'/'+p);sourceControls.push({path:p,bytes:b.length,sha256:sha(b)});}
await fs.writeFile(root+'/'+dir+'/source-controls.json',JSON.stringify(sourceControls,null,2)+'\n',{flag:'wx'});
await fs.writeFile(root+'/'+dir+'/planning-provenance.json',JSON.stringify({atUtc:at,authorization:'Current human request: prepare S2 scheme and automatic PRE per existing selected strategy; no material scope/spec change',baseline:m.head,scheme,schemeSha256:sha(Buffer.from(text)),changedArtifacts:changed,sourceControls:dir+'/source-controls.json',productionChanged:false,pre:'NOT_RUN',readyForVerify:false,progress:'3/9'},null,2)+'\n',{flag:'wx'});
await fs.copyFile(process.argv[1],root+'/'+dir+'/author-s2.mjs',fs.constants.COPYFILE_EXCL);
const oldStatus=await fs.readFile(root+'/'+m.status,'utf8');await fs.writeFile(root+'/'+m.status,`# P02 — S2 scheme prepared; validation / PRE pending\n\n${at}; branch codex/frade-ui-design-contract; worktree ${root}; common E:/dev/codex/frade/.git; original98f387f96b51b0ad139e3507c376ff1c3e8dec09/P02baseline0ecaf44938382bd8daa7d512887dda8a8ee9b372. Guide1.0. Published checkpoint${m.head}.\n\nS1 current focused POST PASS; original historical FAIL and exact deferred P02-D01 causeNOT_PROVEN retained. S2 [scheme](../../${scheme}) prepared: existing backend, immutable ZIP bytes, one journal/reserve8records8MiB, COMMITTED-only recovery, P01 port guard and named Main bridge. No production edits; source controls saved. P023/9;2.2storage/journal/filepicker/bridge,2.3actualrecovery,2.4ExtensionsUI,3.1checks/visual,3.2fullverify/cumulativePOST,3.3archive unfinished.\n\nNext actual strict validation → automatic fresh PRE gpt-6-sol/xhigh → record result. S2 implementation/checks/POST NOT_RUN; fullREADY_FOR_VERIFY:NO. NoP03/Routingdependency. Planning NOT_COMMITTED/PUSHED; panel queued/visibilityunconfirmed. MergeprotectionLOCAL_ONLY/NOT_CONFIGURED.\n\n## Previous entries — preserved\n\n`+oldStatus);
m.s2={atUtc:at,dir,scheme,schemeSha256:sha(Buffer.from(text)),baseline:m.head,sourceControls:dir+'/source-controls.json',PRE:'NOT_RUN'};m.phase='P02_S2_SCHEME_PREPARED';await fs.writeFile(state,JSON.stringify(m,null,2)+'\n');console.log(JSON.stringify({dir,scheme,schemeSha256:m.s2.schemeSha256,sourceControls:sourceControls.length,productionChanged:false,progress:'3/9'}));
