import fs from 'node:fs';import assert from 'node:assert/strict';assert.equal(process.cwd().replaceAll('\\','/'),'C:/Users/NVISEN/.codex/worktrees/ui-design-contract/frade');const m=JSON.parse(fs.readFileSync('C:/Users/NVISEN/AppData/Local/Temp/frade-ui-p02-current.json')),d=m.base+'/evidence/p02-platform-test-hook-implementation-'+new Date().toISOString().replace(/[-:.]/g,'');fs.mkdirSync(d);const p='packages/extension-service/scripts/build-windows-filesystem.mjs',old=fs.readFileSync(p,'utf8');fs.writeFileSync(d+'/build-script-before.txt',old,{flag:'wx'});let s=old.replace("import { spawnSync } from 'node:child_process'","import { spawnSync } from 'node:child_process'\nimport { createRequire } from 'node:module'");const a="const sha = value => crypto.createHash('sha256').update(value).digest('hex')";assert.equal(s.split(a).length,2);s=s.replace(a,a+"\nconst modes = process.argv.slice(2)\nif (modes.length > 1 || (modes.length === 1 && !['--test', '--bdd'].includes(modes[0]))) throw Error('INVALID_BUILD_MODE')");s+=`\nif (modes.length === 1) {
  const files = ['tests/archive.bdd.test.ts', 'tests/filesystem.protocol.test.ts']
  if (process.platform === 'win32') files.push('tests/filesystem.windows.test.ts', 'tests/filesystem.deployment.test.ts')
  else console.log(JSON.stringify({ status: 'WINDOWS_NATIVE_NOT_RUN', portable: 'RUNNING', mode: modes[0] }))
  const runner = createRequire(import.meta.url).resolve('vitest/vitest.mjs')
  const result = spawnSync(process.execPath, [runner, 'run', ...files], { cwd: root, stdio: 'inherit', windowsHide: true, timeout: 240000 })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}
`;fs.writeFileSync(p,s);const pkg='packages/extension-service/package.json',aPkg=JSON.parse(fs.readFileSync(pkg));assert.equal(aPkg.scripts.test,'vitest run');assert.equal(aPkg.scripts['test:bdd'],'vitest run tests/*.bdd.test.ts');aPkg.scripts.test='node scripts/build-windows-filesystem.mjs --test';aPkg.scripts['test:bdd']='node scripts/build-windows-filesystem.mjs --bdd';fs.writeFileSync(pkg,JSON.stringify(aPkg,null,2)+'\n');fs.writeFileSync(d+'/root-cause.json',JSON.stringify({classification:'INTEGRATION_TEST',rawFAIL:m.base+'/evidence/p02-check-service-bdd-before-platform-hook-20261010T094308433Z',rootCause:'Windows package script passes literal wildcard to Vitest which reports no test files; hook also failed to include accepted portable/native proofs.',repair:'Existing authorized build script owns exact --test/--bdd modes; build first on Windows, dispatch explicit archive/protocol/native/deployment via installed Vitest direct Node no shell. Non-Windows explicit portable and WINDOWS_NATIVE_NOT_RUN; no test skips or success masks. Unknown mode refused. No new path/dependency/global setting.',scope:'P02 accepted exact service package manifest/native build script purposes; desktop existing hooks unchanged',capabilities:'NOT_VERIFIED',notClaimed:'Actual non-Windows execution/dev/start/runtime transport/installer integration'},null,2)+'\n',{flag:'wx'});fs.copyFileSync(process.argv[1],d+'/implementation.mjs',fs.constants.COPYFILE_EXCL);console.log(d);
