import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import ts from 'file:///C:/Users/NVISEN/.codex/worktrees/ui-design-contract/frade/apps/desktop/node_modules/typescript/lib/typescript.js';
const sourcePath='packages/ui-workspace/src/design/theme/frameParticipant.ts',raw=fs.readFileSync(sourcePath),source=raw.toString('utf8');
const keys=source.slice(source.indexOf('const phaseKeys ='),source.indexOf('const boundedIdentity ='));
const same=source.slice(source.indexOf('const samePhase ='),source.indexOf('/** Independent frame capability'));
const handler=source.slice(source.indexOf('  const message = (event: MessageEvent)'),source.indexOf('  const stop = (navigate: boolean)'));
if(!keys||!same||!handler.includes('for (const [token, pending] of waiting)'))throw Error('EXTRACTION_MISMATCH');
const compiled=ts.transpileModule(keys+'\n'+same+'\nfunction make(frame,options,waiting,paintedContext){let disposed=false;const origin="frade://drawio";'+handler+'return message;} globalThis.actualHandlerFactory=make;', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
new Function(compiled)();
const counts={resolved:0,rejected:0,invalidated:0,diagnostic:0,cleanup:0},identity={},frame={contentWindow:identity,dataset:{}},options={id:'frame',generation:7,onInvalidated:()=>counts.invalidated++,onRefused:()=>counts.diagnostic++};
const context={version:1,requestId:'window/1',sessionId:'window',generation:1,transactionId:'window/1',revision:1,membership:1,phase:'apply'};
const waiting=new Map([['actual-applied-phase',{operation:'apply',context,status:'PAINTED',cleanup:()=>counts.cleanup++,resolve:()=>counts.resolved++,reject:()=>counts.rejected++}]]),handle=globalThis.actualHandlerFactory(frame,options,waiting,undefined);
const event=(status,message)=>({source:identity,origin:'frade://drawio',data:JSON.stringify({event:'fradePresentation',version:1,participantId:'frame',participantGeneration:7,context,operation:'apply',status,...(message?{message}:{})})});
handle(event('PAINTED'));assert.equal(counts.resolved,1);assert.equal(waiting.size,0);
handle(event('REFUSED','LOWER_MENU_REFLOW_UNAVAILABLE: original targets cannot fit without forbidden behavior'));
const result={classification:'INTEGRATION / STATE_TRANSITION',actualSource:sourcePath,actualSourceSha256:crypto.createHash('sha256').update(raw).digest('hex'),method:'Extract actual current TypeScript handler into memory; no source edits, replacement handler, timers or persisted state. Deliver exact matching PAINTED then REFUSED envelope with same frame/origin/owner/context.',counts,waiting:waiting.size,revision:frame.dataset.fradeRevision,expected:'After completed PAINTED, a matching bounded lower reflow REFUSED must reach an observable diagnostic without changing settled promise/semantic state.',actual:'Refusal dropped after waiting entry cleanup',status:'FAIL'};
fs.writeFileSync(new URL('./result.json',import.meta.url),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));assert.equal(counts.diagnostic,1,'B05 observable diagnostic missing after PAINTED');
