import fs from 'node:fs/promises';import fss from 'node:fs';import path from 'node:path';import os from 'node:os';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {randomUUID,createHash} from 'node:crypto';
const m=JSON.parse(fss.readFileSync('C:/Users/NVISEN/AppData/Local/Temp/frade-ui-p02-current.json')),dir=m.nativeRenameRcaDir,parent=await fs.realpath(os.tmpdir()),temp=await fs.mkdtemp(path.join(parent,'frade-p02-rename-matrix-')),source=fss.readFileSync('packages/extension-service/native/windows-filesystem.cs','utf8'),compiler=path.join(process.env.WINDIR,'Microsoft.NET/Framework64/v4.0.30319/csc.exe');
const nativeImport='  [DllImport("ntdll.dll")] static extern int NtSetInformationFile(IntPtr h,out IoStatus io,IntPtr data,uint length,int type);\n';
const variants=[
['win32-padded',source.replace('total=baseOffset+nameBytes.Length','total=(IntPtr.Size==8?24:16)+nameBytes.Length+2')],
['nt-padded-held-parent',(nativeImport+source).replace(nativeImport,'').replace('  static void Check(bool value)',nativeImport+'  static void Check(bool value)').replace('total=baseOffset+nameBytes.Length','total=(IntPtr.Size==8?24:16)+nameBytes.Length+2').replace('Check(SetFileInformationByHandle(w.Handle,3,buffer,(uint)total));','IoStatus ios;int status=NtSetInformationFile(w.Handle,out ios,buffer,(uint)total,10);if(status<0)throw new Win32Exception((int)RtlNtStatusToDosError(status));')],
['nt-padded-same-source-parent',(nativeImport+source).replace(nativeImport,'').replace('  static void Check(bool value)',nativeImport+'  static void Check(bool value)').replace('total=baseOffset+nameBytes.Length','total=(IntPtr.Size==8?24:16)+nameBytes.Length+2').replace('Marshal.WriteIntPtr(buffer,IntPtr.Size==8?8:4,parent.Handle);','Marshal.WriteIntPtr(buffer,IntPtr.Size==8?8:4,IntPtr.Zero);').replace('Check(SetFileInformationByHandle(w.Handle,3,buffer,(uint)total));','IoStatus ios;int status=NtSetInformationFile(w.Handle,out ios,buffer,(uint)total,10);if(status<0)throw new Win32Exception((int)RtlNtStatusToDosError(status));')],
];const results=[];
try{for(const [name,code] of variants){const cs=path.join(temp,name+'.cs'),exe=path.join(temp,name+'.exe'),root=path.join(temp,name+'-root');await fs.writeFile(cs,code);await fs.mkdir(root);const build=spawnSync(compiler,['/nologo','/target:exe','/platform:x64','/warnaserror+','/reference:System.Web.Extensions.dll','/out:'+exe,cs],{encoding:'utf8',windowsHide:true});assert.equal(build.status,0,build.stdout);fss.writeFileSync(dir+'/'+name+'.fixture.cs',code,{flag:'wx'});
const child=spawn(exe,[],{windowsHide:true,stdio:'pipe'}),session=randomUUID();let text='',id=0,pending;const replies=[];child.stdout.on('data',b=>{text+=b.toString();let n=text.indexOf('\n');if(n>=0&&pending){const r=JSON.parse(text.slice(0,n));text=text.slice(n+1);const cb=pending;pending=null;cb(r);}});const send=(operation,fields={})=>new Promise(resolve=>{pending=resolve;child.stdin.write(JSON.stringify({version:1,session,generation:1,requestId:++id,deadlineMs:10000,operation,...fields})+'\n');});
try{replies.push(await send('bind',{root}));replies.push(await send('mkdir',{path:['records']}));const data=Buffer.from('first-owned-record'),sha=createHash('sha256').update(data).digest('hex'),opened=await send('write-open',{path:['records','pending.tmp'],maxBytes:data.length});replies.push(opened);replies.push(await send('write-chunk',{handle:opened.handle,offset:0,data:data.toString('base64')}));replies.push(await send('write-close',{handle:opened.handle,sha256:sha}));replies.push(await send('replace',{handle:opened.handle,parent:['records'],name:'final.json',sha256:sha}));replies.push({actualNames:await fs.readdir(path.join(root,'records'))});}
finally{if(child.exitCode===null&&child.signalCode===null){const closed=new Promise(r=>child.once('close',r));child.kill();await closed;}}results.push({variant:name,sourceSha256:createHash('sha256').update(code).digest('hex'),buildExit:build.status,replies});}}
finally{const resolved=await fs.realpath(temp);assert.equal(path.dirname(resolved).toLowerCase(),parent.toLowerCase());assert(path.basename(resolved).startsWith('frade-p02-rename-matrix-'));await fs.rm(resolved,{recursive:true});}
fss.writeFileSync(dir+'/rename-matrix.json',JSON.stringify({atUtc:new Date().toISOString(),results,fixtureRemoved:true,productionUnchanged:true,claims:'Diagnostic variants only; no permission or capability acceptance'},null,2)+'\n',{flag:'wx'});fss.copyFileSync(process.argv[1],dir+'/rename-matrix.mjs',fss.constants.COPYFILE_EXCL);console.log(JSON.stringify(results.map(r=>({variant:r.variant,publication:r.replies.at(-2),actual:r.replies.at(-1)}))));
