import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const base='openspec/changes/frade-p01-theme-core',rel=process.argv[2];assert(/^openspec\/changes\/frade-p01-theme-core\/evidence\/p01-focus-context-diagnostic-run-\d{8}T\d{6}Z$/.test(rel||''));const dir=path.resolve(rel),read=n=>JSON.parse(fs.readFileSync(path.join(dir,n))),save=(n,v)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'}),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const summary=read('summary.json'),analysis=read('focus-observation-analysis.json'),cases=read('case-results.json'),completion=read('completion.json');assert(summary.integrity&&summary.counts.passed===134&&summary.counts.failed===1&&summary.focusFailureCount===0);
const b05=cases.find(c=>c.ordinal===57);assert(b05.title.includes('P01-B05')&&b05.outcome==='unexpected');
const artifact='artifacts/ui-contract-theme-P01-CONT-e8421-its-original-feasible-retry',observation=read(artifact+'/b05-observations.json').observations[0];assert(observation.label==='actual-refusal'&&observation.restored.restored===false&&observation.restored.mismatches.length===1);
const manifestPath=base+'/evidence/p01-refresh-full-root-20261008T034000Z/source-before.json',manifest=JSON.parse(fs.readFileSync(manifestPath)),drift=manifest.files.flatMap(f=>{const b=fs.readFileSync(f.path);return b.length===f.bytes&&sha(b)===f.sha256?[]:[{path:f.path,expected:f.sha256,actual:sha(b)}]}),pins=summary.protectedFiles.map(p=>({...p,actual:sha(fs.readFileSync(p.path))}));assert(!drift.length&&pins.every(p=>p.expected===p.actual));
save('source-at-analysis.json',{atUtc:new Date().toISOString(),manifestPath,count:manifest.files.length,drift,protectedFiles:pins,status:'PASS',note:'Separate later integrity read; no earlier completion timestamp changed.'});
const preservation=analysis.map(c=>{assert(c.intact&&c.preservedInitialFinalEquality.files&&c.preservedInitialFinalEquality.identity&&c.perScenarioPreservation.every(p=>p.exact));const x=c.semanticDifferences.find(d=>d.path==='/xml');return {ordinal:c.testOrdinal,title:c.title,filesExact:true,identityExact:true,perScenario:c.perScenarioPreservation,wholeLiveViewDifferences:c.semanticDifferences,xmlOnlyDyDiff:x?x.before.replace(/dy="[^"]*"/g,'dy="ANALYSIS_ONLY"')===x.after.replace(/dy="[^"]*"/g,'dy="ANALYSIS_ONLY"'):null};});
assert(preservation.every(c=>!c.wholeLiveViewDifferences.length||c.xmlOnlyDyDiff));save('preservation-detail.json',{atUtc:new Date().toISOString(),captures:preservation,note:'No assertion or evidence normalized. Whole031 live viewport dy/translate.y/scroll.top changes518->501 compact and511->480 comfortable across original viewport scenarios.42 original per-scenario comparisons pass; all persisted files/identities exact. Whole-series live view equality is not claimed.'});
const facts={atUtc:new Date().toISOString(),status:'OPEN_REPRODUCED_ASSERTION_FAILURE_ROOT_CAUSE_NOT_PROVEN',runtimeCase:57,result:b05.results,observation,source:{test:'apps/desktop/tests/e2e/ui-contract-theme.spec.ts',line:3437,sha256:sha(fs.readFileSync('apps/desktop/tests/e2e/ui-contract-theme.spec.ts')),bridge:'apps/desktop/src/main/drawio-theme-bridge.ts',bridgeSha256:sha(fs.readFileSync('apps/desktop/src/main/drawio-theme-bridge.ts'))},trace:{path:artifact+'/trace.zip',sha256:sha(fs.readFileSync(path.join(dir,artifact,'trace.zip'))),entries:[{name:'resources/src@540b44db646a8e97ddab33c1c220f95b3bbd7c96.txt',bytes:496444},{name:'resources/1e89b4b33e4731559781cce80ade5cdf09a43eae',bytes:43532},{name:'test.trace',bytes:29017}],observed:'expect@69 fails restored boolean; earlier live status/iframe/menu count/aria-expanded/identity/menuGone assertions pass. Trace has test API steps and source/screenshot, no per-writer DOM mutation provenance.'},classification:'UNRESOLVED between TEST baseline capture and adapter STATE_TRANSITION/ABSTRACTION_BOUNDARY; no ENVIRONMENT or product defect attribution proved',hypotheses:[{kind:'TEST',text:'Existing MutationObserver retains the first oldValue for each entire attribute; that may include vendor or earlier-layout writes rather than the specific bridge-owned property lease. Actual writer/timing is not captured.'},{kind:'STATE_TRANSITION',text:'Bridge projectStyle saves per-property value/priority; restoreMenuLayout restores/deletes layout entries before remeasurement, and forgetPopup cancels then restores remaining records. A lease loss/order defect needs direct proof.'}],staticReferences:[{file:'apps/desktop/src/main/drawio-theme-bridge.ts',lines:[521,539,624,744,761,818]},{file:'apps/desktop/tests/e2e/ui-contract-theme.spec.ts',lines:[3408,3430,3437]},{file:'apps/desktop/vendor/drawio/mxgraph/src/util/mxPopupMenu.js',lines:[434,591]},{file:'apps/desktop/vendor/drawio/mxgraph/src/util/mxUtils.js',lines:[1838]}],notReached:'B05 assertions after restored equality, persisted semantic checks, failed publication and feasible retry tail were not executed in this case; no preservation/retry PASS is inferred for B05.',repair:'NOT_IMPLEMENTED; do not change expected65px to0px or weaken whole restoration assertion',next:'Read-only causality audit then a bounded approved diagnostic plan/fresh PRE if additional observations are needed. Existing accepted lower reflow/refusal contracts remain exact; no source change under focus diagnostic authority.'};save('b05-rca-facts.json',facts);
const workers=cases.map(c=>({ordinal:c.ordinal,title:c.title,worker:c.results[0]?.workerIndex,status:c.results[0]?.status}));save('assessment.json',{atUtc:new Date().toISOString(),runtimeStatus:'FAIL',counts:summary.counts,focusStatus:'NOT_REPRODUCED_ROOT_CAUSE_NOT_PROVEN',focusCases:12,focusCaptureIntegrity:'PASS36contexts',b05Status:facts.status,sourceIntegrity:'PASS3479plus4pins',workerChanges:workers.filter((c,i)=>i===0||c.worker!==workers[i-1].worker),limitations:['Original case/order135 reproduced, normal worker restart retained. B05 case57 failed in worker0; cases58-135 including all observed focus cases used worker1. This is an observed lifecycle difference, not proof of a cause.','No root static/unit/BDD/Draw/build rerun; diagnostic is not check:all.','Original full-root2focusFAIL remain unresolved.','Source/backend requested reviewer gpt-6-astra/xhigh; actual backend/effort NOT_CONFIRMED under adopted policy.'],P01:'5/10',readyForVerify:false});
const report='# P01 full-desktop focus context diagnostic — FAIL\n\n'+
'CHANGE: frade-p01-theme-core; branch codex/frade-ui-design-contract; guide1.0/tokens1.0.0. Foundation archived, P01 remains5/10, P02–P07 NOT_STARTED. Routing independent.\n\n'+
'IMPLEMENTED: the single PRE-approved V3 diagnostic execution. All135 cases ran once in the original desktop order, with no retries.92 temporary copies preserved original actions/assertions/timeouts;43 other tests were unchanged. Only12 upper-focus copies had passive observations. No product or permanent fixture repair.\n\n'+
'FILES CHANGED: this dated evidence directory, docs/ui/UI-DESIGN-CONTRACT-STATUS.md, execution-context.json and the prior PRE publication receipt. The original279962-byte E2E file is restored exactly;3479source entries and4source/build pins match, also rechecked at analysis time. Canonical proposal/design/spec/tasks and all foreign worktrees are unchanged.\n\n'+
'TESTS ADDED: temporary diagnostic copies removed. Original discovery135/zero diagnostic names; exact selected-case mapping retained. Earlier V2 PRE FAIL B1, V3 correction and fresh independent PRE PASS remain immutable in their own directories.\n\n'+
'COMMANDS EXECUTED: pinned pnpm12.6.0 --filter @frade/desktop exec playwright test --workers=1 --retries=0 --repeat-each=1 with the exact saved grep and JSON reporter; selection and restored --list; source/hash/artifact/record analysis; git status/diff/diff --check. Exact argv/stdout/stderr/start/completion records are saved. Root static/unit/BDD/Draw/build were not rerun by this diagnostic; the unchanged hashed app binary was used.\n\n'+
'TEST RESULTS: 134PASS/1FAIL,135executions,0retry/skip/timeout;57.6minutes. Case57 P01-B05 fails exact restoration of a lower popup style: expected prior left65px, actual0px. Same identity/menuGone/vendor classes pass; one mismatch is recorded. Later B05 assertions, including persistence and feasible retry, were not reached. [B05 facts](b05-rca-facts.json) distinguish observations from TEST versus adapter hypotheses; no writer/causal attribution is proved and the assertion remains unchanged.\n\n'+
'All12 upper-focus cases pass with complete records in36root/frame/native contexts; no observer errors, overflow, missing final or cleanup failure. No target replacement or native-background state/event was observed. Original full-root focus failures96/100 were NOT_REPRODUCED and remain ROOT_CAUSE_NOT_PROVEN. The B05 failure caused the original Playwright worker restart after57; observed focus cases used worker1. Thus exact case order is confirmed, while identical worker history to the prior failing root is not claimed. No repeated run is authorized merely to seek green.\n\n'+
'All12 focus-case persisted file/identity comparisons and42 original per-scenario preservation comparisons pass. Whole031 live-view values change with existing viewport scenarios: dy/translate.y/scroll.top518->501 in Compact and511->480 in Comfortable; other XML text is exact. [Preservation detail](preservation-detail.json) retains exact values. This is not a whole-series semantic-equality claim or a new exception. No B05 preservation claim is substituted from these separate cases.\n\n'+
'Benchmark PASS p95=130.89999999850988ms<=150, recomputed from100samples after20warmups. WMI display endpoints2560x1440/60Hz unchanged; user reported60.01Hz. Historical4K29Hz203.5ms FAIL and126.4/145.7ms PASS remain. Resolution and refresh changed together; causal contribution is not isolated.\n\n'+
'Applicable focus/contrast/keyboard/reflow/preservation rules: FDS-003/004/005/007/009/010, A11Y-001/002/003/005/007/008 and exact accepted P01 lower reflow/refusal and upper focus scopes.4753artifact files/530082961bytes hashed; all mtimes belong to this run. These results are not full UI/A11Y compliance or human visual approval.\n\n'+
'Screenshots inspected: [B05 actual refusal](artifacts/ui-contract-theme-P01-CONT-e8421-its-original-feasible-retry/test-failed-1.png), [Dark/Comfortable View focus](artifacts/ui-contract-theme-P01-CONT-daaf0-cus-raster-dark-comfortable/viewPanels-focus.png), [Light/Comfortable wide View focus](artifacts/ui-contract-theme-P01-CONT-6aa08-and-modal-light-comfortable/wide-viewPanels.png). Actual Electron captures; visual acceptance NOT_APPROVED.\n\n'+
'Environment/tool distinction: restricted exec git status/diff returned \"this operation must be run in a work tree\" while rev-parse recognized the registered non-bare worktree. The same commands succeeded in the authorized UI exec context without Git configuration changes. This resolved tooling limitation is separate from the reproducible B05 assertion result. An interrupted first analyzer tool call wrote no evidence; the actual analyzer then completed and saved its outputs once.\n\n'+
'KNOWN BLOCKERS: original full-root2focusFAIL unresolved; current diagnostic1B05FAIL unresolved. No production change, test weakening, routing dependency or gate waiver. Tasks2.4/2.5/3.1 remain open; OpenSpec verify BLOCKED, cumulative POST NOT_RUN, human visual NOT_APPROVED, archive BLOCKED.\n\n'+
'NEXT: stop focus sampling under the completed plan; continue B05 cause analysis using the preserved actual failure. Any new executable diagnostic or remedy needs a bounded coherent plan and fresh independent PRE. A material new scope/contract boundary requires a human decision; routine read-only analysis does not. No display/configuration action is presently required from the user.\n\nREADY_FOR_VERIFY: NO\n';
fs.writeFileSync(path.join(dir,'report.md'),report,{flag:'wx'});fs.copyFileSync(process.argv[1],path.join(dir,'record-outcome.mjs'),fs.constants.COPYFILE_EXCL);
const status='docs/ui/UI-DESIGN-CONTRACT-STATUS.md';let s=fs.readFileSync(status,'utf8');s=s.replace(/^# P01:.*$/m,'# P01: diagnostic134PASS/1FAIL; B05 restoration RCA').replace(/^Обновлено .*?\. Ветка/m,'Обновлено '+new Date().toISOString()+'. Ветка').replace(/^\| RCA \|.*$/m,'| RCA | Desktop diagnostic134PASS/1B05FAIL; all12focus cases PASS/36complete contexts. Original focus NOT_REPRODUCED / ROOT_CAUSE_NOT_PROVEN; new B05 cause OPEN |').replace(/^\| Current benchmark \|.*$/m,'| Current benchmark | Diagnostic PASS p95=130.9ms<=150,100samples/recomputed; previous full root126.4ms and focused145.7ms PASS. Historical4K29Hz203.5ms FAIL retained |').replace(/^\| Source \/ binary \/ display endpoints \|.*$/m,'| Source / binary / display endpoints | Exact original whole E2E restored;3479sources +4pins exact at completion and analysis; original discovery135/0diagnostic;2560×1440/60Hz endpoints unchanged |').replace(/^\| Evidence integrity \|.*$/m,'| Evidence integrity | Current diagnostic4753fresh hashed artifacts/530082961bytes;12complete focus captures/36contexts. Original full4687artifacts retained |').replace(/^\| Tasks2.4 \/2.5 \/3.1 \|.*$/m,'| Tasks2.4 /2.5 /3.1 | OPEN; original full focus FAIL2 unresolved; new diagnostic B05 restoration FAIL. Human visual NOT_APPROVED |').replace(/^Следующий шаг:.*$/m,'Следующий шаг: RCA B05 по сохранённому actual FAIL; отличить property lease/rollback адаптера от baseline whole-attribute observer в тесте. Cause NOT_PROVEN. Новая executable диагностика/repair — только bounded plan + fresh PRE; исходное утверждение не ослаблять. Focus sampling завершён; P02 не начинается. Действий человека с дисплеем сейчас не нужно.').replace(/^Git:.*$/m,'Git: PRE checkpoint a715b57f70c59b350ae19440bfd9ea00db56e7ae already PUSHED_REMOTE_SHA_VERIFIED. Completed diagnostic134PASS/1B05FAIL evidence/status await authorized commit/push. Product diff empty. Branch protection LOCAL_ONLY/NOT_CONFIGURED; right panel queued, visibility unconfirmed.');
s=s.replace('| New blocker2 | Light/Comfortable body focus: baseline3passed; first View focus after wide viewport inactive,10000ms |','| New blocker2 | Light/Comfortable body focus: baseline3passed; first View focus after wide viewport inactive,10000ms |\n| New blocker3 | Diagnostic case57 B05: exact lower-popup restoration FAIL; inline left expected65px/actual0px. Identity/menuGone/vendor classes pass; later B05 assertions NOT_REACHED. Cause NOT_PROVEN |');
const marker='## История (неизменённые прежние записи)';s=s.replace(marker,'Текущий diagnostic: [отчёт](../../'+rel+'/report.md), [assessment](../../'+rel+'/assessment.json), [B05 RCA](../../'+rel+'/b05-rca-facts.json). 134PASS/1FAIL; этот результат не закрывает historical full gateFAIL2.\n\n'+marker);fs.writeFileSync(status,s);
const cp=base+'/execution-context.json',c=JSON.parse(fs.readFileSync(cp));c.phase='P01_DIAGNOSTIC_FAIL_B05_RESTORATION_RCA';c.currentFocusContextDiagnostic={...c.currentFocusContextDiagnostic,status:'COMPLETED_FAIL_B05_FOCUS_NOT_REPRODUCED',execution:'COMPLETED',counts:summary.counts,completion,summary:rel+'/summary.json',assessment:rel+'/assessment.json',report:rel+'/report.md',sourceAtAnalysis:rel+'/source-at-analysis.json',focus:'12PASS_36COMPLETE_CONTEXTS_ROOT_CAUSE_NOT_PROVEN',progress:{...c.currentFocusContextDiagnostic.progress,completedOutcomes:'134PASS_1B05FAIL',finishedAtUtc:completion.atUtc}};c.currentFocusRca.status='ROOT_CAUSE_NOT_PROVEN';c.currentLowerB05RestorationRca={status:facts.status,facts:rel+'/b05-rca-facts.json',actual:{case:57,expectedLeft:'65px',actualLeft:'0px'},sourceChanged:false,next:'READ_ONLY_CAUSE_AUDIT_THEN_BOUNDED_PLAN_FRESH_PRE_BEFORE_NEW_EXECUTABLE_DIAGNOSTIC_OR_REPAIR'};fs.writeFileSync(cp,JSON.stringify(c,null,2)+'\n');
const checks=[];for(const [name,args]of [['status',['status','--short','--branch']],['diff-check',['-c','core.whitespace=blank-at-eol,blank-at-eof,space-before-tab,cr-at-eol','diff','--check']],['diff-stat',['diff','--stat']],['product-diff',['diff','--exit-code','--','apps','packages','scripts','tests','package.json','pnpm-lock.yaml','pnpm-workspace.yaml','turbo.json']]]){const command=['git','-c','core.longpaths=true','-c','core.autocrlf=false',...args],r=spawnSync(command[0],command.slice(1),{encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});fs.writeFileSync(path.join(dir,name+'-stdout.txt'),r.stdout,{flag:'wx'});fs.writeFileSync(path.join(dir,name+'-stderr.txt'),r.stderr,{flag:'wx'});checks.push({name,command,exitCode:r.status});assert.equal(r.status,0,name)}save('git-checks.json',{atUtc:new Date().toISOString(),checks});
console.log(JSON.stringify({status:'FAIL_134PASS_1B05FAIL',focus:'NOT_REPRODUCED_ROOT_CAUSE_NOT_PROVEN',sourceCount:manifest.files.length,sourcePass:true,checks:checks.map(x=>[x.name,x.exitCode]),report:rel+'/report.md'}));
