import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {spawn,execFileSync} from 'node:child_process';import {createWriteStream} from 'node:fs';import {finished} from 'node:stream/promises';
const base=import.meta.dirname,root='E:/dev/codex/frade-worktrees/frade-standard-workflow',rel='openspec/changes/frade-standard-workflow',work=path.join(base,'work'),input=path.join(base,'input'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const job=JSON.parse(await fs.readFile(path.join(base,'job.json'),'utf8'));const probe=JSON.parse(await fs.readFile(path.join(base,'receipt.json'),'utf8'));if(probe.status!=='PASS')throw Error('Confinement not proven');
const plan=await fs.readFile(path.join(root,rel,'design.md'));if(sha(plan)!=='501168ced50a35e128a0fc86e79bab6ac9aa31cd343eca3eedac56f81570978a'||!plan.toString().includes('| W01 | tooling-tests | gpt-6-sol | high |'))throw Error('Exact assignment drift');
const bindings=[];async function copy(from,to){const bytes=await fs.readFile(from);await fs.mkdir(path.dirname(to),{recursive:true});await fs.writeFile(to,bytes,{flag:'wx'});bindings.push({path:path.relative(input,to).replaceAll('\\','/'),sha256:sha(bytes),bytes:bytes.length,original:from});}
const files=['AGENTS.md','package.json',...['proposal.md','design.md','tasks.md','traceability.json','drafts/direction-manifest.example.json','drafts/standard-workflow.md','drafts/newcomer-guide.md','drafts/status-template.md','evidence/user-decisions.json','evidence/check-applicability.json','evidence/shared-policy/agent-workflow.md','evidence/shared-policy/parallel-feature-workflow.md','evidence/reviews/formal-pre-01-pass/receipt.json','evidence/reviews/formal-pre-01-pass/output/result.md','evidence/task-2.1-controller-inspection.json','evidence/task21-additional-shape-probes.json','evidence/implementation-runs/task-2.1-repair/windows-core-green.json','evidence/implementation-runs/task-2.1-repair/windows-regression-red.json'].map(p=>rel+'/'+p),...['engineering-direction-lifecycle','engineering-role-dispatch','engineering-progress-publication'].map(s=>rel+'/specs/'+s+'/spec.md')];
for(const p of files)await copy(path.join(root,p),path.join(input,p));
async function tree(from,to,seed=false){for(const e of await fs.readdir(from,{withFileTypes:true})){if(e.isSymbolicLink())throw Error('Input link');const a=path.join(from,e.name),b=path.join(to,e.name);if(e.isDirectory())await tree(a,b,seed);else if(e.isFile()){await copy(a,b);if(seed){const q=path.join(work,path.relative(path.join(input,'seed'),b));await fs.mkdir(path.dirname(q),{recursive:true});await fs.copyFile(b,q);}}}}
const prior=JSON.parse(await fs.readFile(path.join(job.priorRun,'execution.json'),'utf8'));if(prior.status!=='EXECUTED'||!prior.inputUnchanged)throw Error('Prior execution incomplete');
for(const dir of ['scripts/directions','tests/directions','docs/engineering/templates'])await tree(path.join(job.seedRoot,dir),path.join(input,'seed',dir),true);
await tree(path.join(job.seedRoot,'deliverables/repair-red'),path.join(input,'history','deliverables/repair-red'));
for(const p of ['TASK-2.1-REPAIR-RESULT.json'])await copy(path.join(job.seedRoot,p),path.join(input,'history',p));
await copy('E:/dev/codex/frade/.agents/skills/openspec-apply-change/SKILL.md',path.join(input,'skills','openspec-apply-change','SKILL.md'));
await fs.writeFile(path.join(work,'package.json'),JSON.stringify({private:true,type:'module'})+'\n',{flag:'wx'});
const head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
await fs.writeFile(path.join(input,'EXECUTION-INPUTS.json'),JSON.stringify({stage:'W01',task:job.task,approvedModel:'gpt-6-sol',approvedEffort:'high',planSha256:sha(plan),source:rel+'/design.md',sourceExcerpt:'| W01 | tooling-tests | gpt-6-sol | high |',bindings,ownerHead:head},null,2)+'\n',{flag:'wx'});
const prompt="You are the exact approved W01 tooling-tests executor invoked gpt-6-sol/high. Actual backend/effort NOT_CONFIRMED. Formal PRE and human policy acceptance retained. Complete ONLY the last scoped task2.1 argument-boundary defect. Immutable authorized input is /mnt/e/dev/codex/frade/.git/frade-workflow/implementations/w01-task-2.1-arguments-20261002/input; seeded code/tests are in work. Read complete proposal/design/three specs/tasks plus adopted policies and input skill. Work write only, root deny, input/harness read-only, no original/other checkout/common/auth/settings/network/apps; fresh canary passed.\nThe prior repair is complete and all30 named cases passed ACTUAL Windows Node24, but a required controller probe found validateApplicability(null) throws TypeError instead of returning APPLICABILITY_SHAPE. No production imported. Fix this legitimate current API issue before closing2.1. Do NOT reimplement closure, bootstrap, roles or documentation architecture.\nWrite one meaningful regression file first, run behavior RED against current seeded modules and retain exact new test snapshot plus pre-fix modules and command logs under deliverables/arguments-red. Null/scalar options at untrusted data guard entrypoints (validateApplicability, verifyApplicability, evaluateTransition, planClosure, executeClosure) must reject with stable structured invalid result before reading/writing, not crash. Preserve intentional documented throwing factories and fingerprint function for invalid programmer inputs; never turn invalid hashes into approval. Add appropriate null/scalar positive/negative/boundary assertions without weakening existing30 cases. Then make minimal source repair, run targeted GREEN and full30+new suite, capture full actual exits/logs/environment. Two failed fixes of same deterministic defect require classified RCA before next production edit.\nFinal TASK-2.1-ARGUMENTS-RESULT.json must be concise: eligible changed files, regression test names, actual RED/GREEN command exits/logs, blockers, Windows replay pending. Existing full raw history is immutable; do not regenerate old tests/skeletons or repeat already passed runs without a new source change. Do not self-certify PRE/POST, archive, merge, publish or advance to task2.2. Stop after the small scoped fix.\n";
await fs.writeFile(path.join(base,'prompt.md'),prompt,{flag:'wx'});
const linux=p=>'/mnt/'+p[0].toLowerCase()+p.slice(2).replaceAll('\\','/'),runtime='/mnt/c/Users/NVISEN/.codex/review-automation/packet-v1-20261001T061101Z/linux-runtime';
const args=['-d','Ubuntu-22.04_E','--exec','/usr/bin/env','CODEX_HOME=/mnt/c/Users/NVISEN/.codex',runtime+'/node_modules/.bin/codex','exec','--ignore-user-config','--ignore-rules','--ephemeral','--skip-git-repo-check','--model','gpt-6-sol',...probe.configs.flatMap(c=>['-c',c]),'-C',linux(work),'--json','--color','never','--output-last-message',linux(path.join(base,'result.md')),'-'];
const record={startedAtUtc:new Date().toISOString(),stage:'W01',task:job.task,role:'tooling-tests',approvedModel:'gpt-6-sol',approvedEffort:'high',requestedModel:'gpt-6-sol',requestedEffort:'high',actualBackend:'NOT_CONFIRMED',actualEffort:'NOT_CONFIRMED',sandboxProbeSha256:sha(await fs.readFile(path.join(base,'receipt.json'))),inputManifestSha256:sha(await fs.readFile(path.join(input,'EXECUTION-INPUTS.json'))),promptSha256:sha(Buffer.from(prompt)),args,status:'RUNNING'};await fs.writeFile(path.join(base,'request.json'),JSON.stringify(record,null,2)+'\n',{flag:'wx'});
const child=spawn('wsl.exe',args,{cwd:base,shell:false,windowsHide:true}),out=createWriteStream(path.join(base,'events.jsonl'),{flags:'wx'}),err=createWriteStream(path.join(base,'stderr.txt'),{flags:'wx'});child.stdout.pipe(out);child.stderr.pipe(err);child.stdin.on('error',e=>record.stdinError=String(e));child.stdin.end(prompt);const timer=setTimeout(()=>{record.timedOut=true;child.kill()},2400000);record.exitCode=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',resolve)});clearTimeout(timer);await Promise.all([finished(out),finished(err)]);
let intact=true;for(const b of bindings)if(sha(await fs.readFile(path.join(input,b.path)))!==b.sha256)intact=false;record.inputUnchanged=intact;const events=(await fs.readFile(path.join(base,'events.jsonl'),'utf8')).split(/\r?\n/).filter(Boolean).map(s=>JSON.parse(s));record.completeStream=events.some(e=>e.type==='turn.completed')&&!events.some(e=>e.type==='turn.failed'||e.type==='error');record.status=record.exitCode===0&&record.completeStream&&intact&&!record.timedOut&&!record.stdinError?'EXECUTED':'BLOCKED';record.endedAtUtc=new Date().toISOString();await fs.writeFile(path.join(base,'execution.json'),JSON.stringify(record,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:record.status,exitCode:record.exitCode,inputUnchanged:record.inputUnchanged,completeStream:record.completeStream,run:base}));process.exitCode=record.status==='EXECUTED'?0:2;
