import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root='openspec/changes/frade-p01-theme-core/evidence/p01-refresh-full-root-20261008T034000Z';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p)),must=(v,m)=>{if(!v)throw Error(m)},save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const result=read(root+'/result.json'),wrapper=read(root+'/wrapper-result.json'),source=read(root+'/source-before.json'),out=fs.readFileSync(root+'/stdout.txt','utf8');
const lines=out.split(/\r?\n/),desktop=lines.filter(l=>/^\s*(ok|x|×|✘|✓)\s+\d+\s+tests\\e2e\\/.test(l)),failures=desktop.filter(l=>!/^\s*(ok|✓)\s/.test(l));
const performancePath=root+'/desktop-artifacts/ui-contract-theme-performa-c8cfa-ernating-requests-p95-150ms/performance-result.json';
const perf=read(performancePath),sorted=perf.samples.map(s=>s.milliseconds).sort((a,b)=>a-b);must(sorted.length===100&&perf.nearestRank===95&&sorted[94]===perf.p95Ms,'PERFORMANCE_RANK_DRIFT');
const currentSource=source.files.map(f=>({...f,currentSha256:sha(fs.readFileSync(f.path))}));const drift=currentSource.filter(f=>f.currentSha256!==f.sha256);
const oldSource=read('openspec/changes/frade-p01-theme-core/evidence/p01-current-full-root-20261007T223204Z/source-before.json');
const samePriorSource=JSON.stringify(oldSource.files)===JSON.stringify(source.files);
const copies=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name).replaceAll('\\','/');if(e.isDirectory())walk(p);else if(e.isFile()){const b=fs.readFileSync(p),original=p.replace(root+'/desktop-artifacts','apps/desktop/test-results').replace(root+'/draw-artifacts','packages/draw/test-results'),s=fs.statSync(original);const originalSha256=sha(fs.readFileSync(original));copies.push({path:p,bytes:b.length,sha256:sha(b),original,originalSha256,copyMatchesOriginal:sha(b)===originalSha256,originalMtimeUtc:s.mtime.toISOString(),freshlyWrittenDuringThisRoot:s.mtimeMs>=Date.parse(result.start)&&s.mtimeMs<=Date.parse(result.end)});}}}
walk(root+'/desktop-artifacts');walk(root+'/draw-artifacts');
const summary={atUtc:new Date().toISOString(),status:result.exitCode===0&&wrapper.exitCode===0&&result.sourceUnchanged&&drift.length===0&&wrapper.displayUnchanged&&desktop.length===135&&failures.length===0&&/215 passed/.test(out)&&perf.status==='PASS'&&copies.every(f=>f.copyMatchesOriginal&&f.freshlyWrittenDuringThisRoot)?'PASS':(result.exitCode!==0?'FAIL':'BLOCKED_INTEGRITY'),command:'pnpm check:all',result,wrapper,desktop:{completed:desktop.length,passed:desktop.length-failures.length,failed:failures.length,failureLines:failures},draw:{passed:/215 passed/.test(out)?215:null},performance:{path:performancePath,sha256:sha(fs.readFileSync(performancePath)),status:perf.status,p95Ms:perf.p95Ms,budgetMs:perf.budgetMs,samples:sorted.length,medianMs:(sorted[49]+sorted[50])/2,minMs:sorted[0],maxMs:sorted.at(-1),above150:sorted.filter(v=>v>150).length,nearestRankRecomputed:true},sources:{count:source.files.length,currentDrift:drift,identicalToPrior4K29HzRoot:samePriorSource},artifacts:{count:copies.length,bytes:copies.reduce((n,f)=>n+f.bytes,0),notFresh:copies.filter(f=>!f.freshlyWrittenDuringThisRoot).map(f=>f.path)},currentContractPins:['openspec/changes/frade-p01-theme-core/proposal.md','openspec/changes/frade-p01-theme-core/design.md','openspec/changes/frade-p01-theme-core/tasks.md','openspec/changes/frade-p01-theme-core/specs/theme-core/spec.md'].map(file=>({file,sha256:sha(fs.readFileSync(file))})),stdoutSha256:sha(fs.readFileSync(root+'/stdout.txt')),stderrSha256:sha(fs.readFileSync(root+'/stderr.txt')),limits:['Single fresh full run in user-selected2560x1440/60Hz.','Resolution and refresh changed together; independent causal contribution and general stability not established.','Historical4K29Hz203.5ms FAIL and diagnostic145.7ms PASS retained.','Turbo cache hits are disclosed in stdout; actual Draw/Desktop E2E executed.','No human visual acceptance or independent cumulative POST inferred.']};
save(root+'/artifacts-manifest.json',{atUtc:new Date().toISOString(),rootEvidence:root,copies});save(root+'/summary.json',summary);fs.copyFileSync(process.argv[1],root+'/summarize.mjs',fs.constants.COPYFILE_EXCL);console.log(JSON.stringify(summary));



