import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn,execFileSync} from 'node:child_process';
const root=process.cwd();
const dir=path.dirname(new URL(import.meta.url).pathname.replace(/^\/(?=[A-Za-z]:)/,''));
const scopedBin=path.join(dir,'runtime-bin');
process.env.Path=scopedBin+path.delimiter+process.env.Path;
process.env.PATH=process.env.Path;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const save=(n,v)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const selected=execFileSync('git',['-c','core.longpaths=true','ls-files','-z','--','apps','packages','scripts','tests','package.json','pnpm-lock.yaml','pnpm-workspace.yaml','turbo.json'],{encoding:'utf8'}).split('\0').filter(p=>p&&!/(^|\/)(openspec|evidence|node_modules|dist|out|test-results)\//.test(p));
const snapshot=()=>selected.map(p=>{const b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:sha(b)}});
const before=snapshot(),start=new Date().toISOString(),head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
save('source-before.json',{atUtc:start,files:before});
save('command.json',{start,head,cwd:root,command:[process.execPath,'E:/Program Files/nodejs/node_modules/corepack/dist/pnpm.js','check:all'],envOverrides:{FRADE_DRAW_E2E_PORT:'53391',pathPrefix:scopedBin,pnpmVersion:'12.6.0'},note:'Full unfiltered root command; original test defaults/assertions. No concurrent Electron fixture. Turbo cache hits disclosed in stdout.'});
const out=fs.openSync(path.join(dir,'stdout.txt'),'wx'),err=fs.openSync(path.join(dir,'stderr.txt'),'wx');
const child=spawn(process.execPath,['E:/Program Files/nodejs/node_modules/corepack/dist/pnpm.js','check:all'],{cwd:root,env:{...process.env,FRADE_DRAW_E2E_PORT:'53391'},windowsHide:true,stdio:['ignore',out,err]});
console.log(JSON.stringify({dir,childPid:child.pid,start,sourceCount:before.length,head}));
const exitCode=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve)});
fs.closeSync(out);fs.closeSync(err);
const after=snapshot();const changed=after.filter((v,i)=>v.sha256!==before[i].sha256);
for(const [source,name] of [['packages/draw/test-results','draw-artifacts'],['apps/desktop/test-results','desktop-artifacts']])if(fs.existsSync(source))fs.cpSync(source,path.join(dir,name),{recursive:true,errorOnExist:true,force:false});
const result={start,end:new Date().toISOString(),exitCode,sourceCount:before.length,sourceUnchanged:changed.length===0,changed};save('result.json',result);console.log(JSON.stringify(result));process.exitCode=exitCode??1;